# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml
#

# This version starts a separte job for each platform config
# in order to get around the AppVeyor limit of 60 mins per job.

# build version format
version: "{build}"

# Free accounts have a max of 1, but ask anyway.
max_jobs: 4

os:
  - Visual Studio 2015

environment:
  PYTHON_PATH: "C:/Python35"
  PYTHON_PACKAGE_PATH: "C:/Python35/Scripts"

branches:
  only:
    - master

before_build:
  - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%"
  - echo.
  - echo Starting build for %APPVEYOR_REPO_NAME%
  # Determine the appropriate CMake generator for the current version of Visual Studio
  - echo Determining VS version
  - python .\scripts\determine_vs_version.py > vsversion.tmp
  - set /p VS_VERSION=< vsversion.tmp
  - echo Detected Visual Studio Version as %VS_VERSION%
  - del /Q /F vsversion.tmp
  - if %PLATFORM% == Win32 (set GENERATOR="Visual Studio %VS_VERSION%")
  - if %PLATFORM% == x64 (set GENERATOR="Visual Studio %VS_VERSION% Win64")
  # Vulkan-Tools
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/KhronosGroup/Vulkan-Tools.git
  - cd Vulkan-Tools
  - mkdir build
  - cd build
  - cmake -G %GENERATOR% ..
  - cmake --build . --config %CONFIGURATION% --target install
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

# Build only x64 Release and Win32(x86) Debug to reduce build time.
# This should still provide adequate 32-bit vs 64-bit and
# Release vs Debug coverage.
matrix:
  exclude:
    - configuration: Release
      platform: Win32
    - configuration: Debug
      platform: x64

build:
  parallel: true               # enable MSBuild parallel builds
  project: build/BRIMSTONE.sln # path to Visual Studio solution or project
  verbosity: quiet             # quiet|minimal|normal|detailed
