
/*
 * Copyright (c) 2025 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

#ifndef GFXRECON_SETTINGS_STRUCT_H
#define GFXRECON_SETTINGS_STRUCT_H

#include <cstdint>
#include <string>

struct GfxrCaptureSettingsStruct
{
    std::string capture_compression_type{"lz4"};
#if defined(__ANDROID__)
    std::string capture_file{"/sdcard/gfxrecon_capture.gfxr"};
#else
    std::string capture_file{"gfxrecon_capture.gfxr"};
#endif
    bool        capture_file_flush{false};
    bool        capture_file_timestamp{true};
    std::string capture_frames{""};
    std::string capture_process_name{""};
    std::string capture_queue_submits{""};
    bool        capture_dynamic_trigger{false};
    bool        capture_dynamic_trigger_dump_assets{false};
    std::string capture_trigger_frames{""};
    bool        capture_use_asset_file{false};
    bool        force_command_serialization{false};
    bool        log_allow_indents{false};
    bool        log_break_on_error{false};
    bool        log_detailed{false};
    bool        log_errors_to_stderr{true};
    std::string log_file{""};
    bool        log_file_create_new{true};
    bool        log_file_flush_after_write{false};
    bool        log_file_keep_open{true};
    std::string log_level{"info"};
    bool        log_output_to_console{true};
    bool        log_timestamps{false};
    std::string memory_tracking_mode{"page_guard"};
    bool        page_guard_copy_on_map{true};
    bool        page_guard_persistent_memory{false};
    bool        page_guard_separate_read{true};
    bool        page_guard_signal_handler_watcher{false};
    int32_t     page_guard_signal_handler_watcher_max_restores{1};
    bool        page_guard_unblock_sigsegv{false};
    bool        queue_zero_only{false};
    bool        quit_after_capture_frames{false};
#if defined(__ANDROID__)
    std::string screenshot_dir{"/sdcard"};
#else
    std::string screenshot_dir{""};
#endif
    std::string screenshot_format{"bmp"};
    std::string screenshot_frames{""};
    int32_t     screenshot_interval{1};

    // D3D12-Specific
    uint32_t    accel_struct_padding{0};
    std::string capture_draw_calls{""};
    bool        capture_iunknown_wrapping{false};
    bool        debug_device_lost{false};
    bool        debug_layer{false};
    bool        disable_dxr{false};
    bool        disable_meta_command{false};
    std::string rv_annotation_descriptor{""};
    bool        rv_annotation_experimental{false};
    std::string rv_annotation_gpuva{""};
    bool        rv_annotation_rand{false};

    // Vulkan-Specific
    bool        allow_pipeline_compile_required{false};
    bool        force_fifo_present_mode{true};
    bool        page_guard_align_buffer_sizes{true};
#if defined(__ANDROID__)
    bool        ignore_frame_boundary_android{false};
#endif // defined(__ANDROID__)
#if defined(__ANDROID__)
    bool        capture_android_dump_assets{false};
    bool        capture_android_trigger{false};
    bool        page_guard_track_ahb_memory{false};
#endif // defined(__ANDROID__)
#if defined(__linux__)
    std::string capture_environment{""};
    std::string capture_trigger{""};
#endif // defined(__linux__)
#if defined(__APPLE__)
    std::string capture_environment{""};
    std::string capture_trigger{""};
#endif // defined(__APPLE__)
#if defined(WIN32)
    std::string capture_environment{""};
    std::string capture_trigger{""};
    bool        log_output_to_os_debug_string{false};
    bool        page_guard_external_memory{false};
#endif // defined(WIN32)

    // OpenXR-Specific
    bool        skip_threads_with_invalid_data{false};
};

struct GfxrSettingsStruct
{
    GfxrCaptureSettingsStruct capture_settings;
};

#endif // GFXRECON_SETTINGS_STRUCT_H

