include $(CLEAR_VARS)
LOCAL_MODULE := gfxrecon_format

LOCAL_SRC_FILES += ${GFXRECON_SOURCE_DIR}/framework/format/format_util.cpp

LOCAL_C_INCLUDES += ${GFXRECON_INCLUDE_DIR}/framework

LOCAL_CFLAGS := -DGFXRECON_ENABLE_LZ4_COMPRESSION -DGFXRECON_ENABLE_ZLIB_COMPRESSION -DGFXRECON_ENABLE_PNG_SCREENSHOT

LOCAL_STATIC_LIBRARIES += platform_specific vulkan_registry gfxrecon_util

include $(BUILD_STATIC_LIBRARY)
