name: CI Build

# Perform CI builds for pull requests targeting the dev branches.

on:
  pull_request:
    branches:
      - dev

jobs:
  windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC Release",
            os: windows-latest,
            artifact: "gfxreconstruct-dev-windows-msvc-release",
            type: "release",
            build_dir: "build",
            cc: "cl", cxx: "cl"
          }
    steps:
      - name: Require Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Ply Python Module
        run: pip install ply
      - name: Run with VsDevCmd
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install SDK 20348
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 20348
      - name: Set WindowsSDKVersion
        run:
          echo ("WindowsSDKVersion=10.0.20348.0\") >> $env:GITHUB_ENV
      - name: Clone repository from merge of PR branch and dev branch
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Check generated code
        run: |
          python3 framework/generated/generate_dx12.py # check generated code isn't out of date
          git diff --exit-code
      - name: Run build script
        run: |
          python scripts\build.py --skip-check-code-style --config ${{ matrix.config.type }} --parallel 0
      - name: Run test app test cases
        run: |
          cd ${{matrix.config.build_dir}}\windows\x64\output\bin
          ./run-tests.ps1
      - name: Prepare artifacts
        run: |
          copy LICENSE.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
          copy LICENSE_ThirdParty.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
          copy USAGE_desktop_D3D12.md ${{ matrix.config.build_dir }}\windows\x64\output\bin\
          copy USAGE_desktop_Vulkan.md ${{ matrix.config.build_dir }}\windows\x64\output\bin\
          copy layer\vk_layer_settings.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
          move ${{ matrix.config.build_dir }}\windows\x64\output\bin gfxreconstruct-dev
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.artifact }}
          path: .\gfxreconstruct-dev
