name: SDK Android Build

# Perform an Android build, create a release, and attach build
# artifacts to the release when a Vulkan SDK tag is pushed. The
# Vulkan SDK does not include binaries for Android, so we publish
# them here to provide Android binaries built from the same source
# used to build the Vulkan SDK.
#
# The tag needs to be pushed by name, as `git push --tags` to push all
# tags does not appear to trigger the action.
#
# The Vulkan SDK release process is similar to the following:
# 1. Add a lightweight tag with the sdk version string.
#        git tag vulkan-sdk-1.2.141.0
# 3. Push the tag to GitHub.
#        git push origin vulkan-sdk-1.2.141.0

on:
  push:
    tags:
      - vulkan-sdk-*

jobs:
  android:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Android Release/Debug",
            os: ubuntu-26.04,
            artifact: "gfxreconstruct-android"
          }
    steps:
    - name: Clone repository
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Set up Java
      uses: "actions/setup-java@v6"
      with:
        java-version: 25
        distribution: "temurin"
    - name: Gradle build
      run: |
        cd android
        sh gradlew -Parm64-v8a :layer:assembleRelease :replay:assembleDebug :multi-win-replay:assembleDebug
    - name: Prepare artifacts
      run: |
        mkdir gfxreconstruct-dev
        mkdir gfxreconstruct-dev/layer
        mkdir gfxreconstruct-dev/tools
        cp LICENSES/LICENSE.txt gfxreconstruct-dev/
        cp LICENSES/LICENSE_ThirdParty.txt gfxreconstruct-dev/
        cp USAGE_android.md gfxreconstruct-dev/
        cp layer/vk_layer_settings.txt gfxreconstruct-dev/
        cp -r android/layer/build/intermediates/cxx/RelWithDebInfo/*/obj/arm64-v8a gfxreconstruct-dev/layer/
        cp android/tools/replay/build/outputs/apk/debug/replay-debug.apk gfxreconstruct-dev/tools/
        cp android/tools/multi-win-replay/build/outputs/apk/debug/multi-win-replay-debug.apk gfxreconstruct-dev/tools/
        cp android/scripts/gfxrecon.py gfxreconstruct-dev/tools/
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-dev

  release:
    name: Create Release for Tag
    runs-on: ubuntu-26.04
    needs: android
    steps:
    - name: Get sdk version string
      id: get_sdk_version
      run: |
        echo "sdk_version=${GITHUB_REF_NAME#vulkan-sdk-}" >> "$GITHUB_OUTPUT"
    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SDK_VERSION: ${{ steps.get_sdk_version.outputs.sdk_version }}
      run: |
        cat > ./release_notes.txt <<EOF
        Android binaries to compliment the desktop binaries distributed with the Vulkan ${SDK_VERSION} SDK.

        Build Info:
        - Android SDK Version: 34 (Android 14)
        - Android NDK Version: 26.3.11579264 (r26d)
        EOF
        gh release create "$GITHUB_REF_NAME" --verify-tag --repo "$GITHUB_REPOSITORY" \
          --title "Android binaries for ${SDK_VERSION} SDK release" \
          --notes-file ./release_notes.txt

  publish:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: release
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Upload Android Release Tar Gzip Artifact",
            os: ubuntu-26.04,
            artifact: "gfxreconstruct-android",
            command: "tar czf",
            suffix: "android.tar.gz"
          }
        - {
            name: "Upload Android Release Zip Artifact",
            os: ubuntu-26.04,
            artifact: "gfxreconstruct-android",
            command: "zip -r",
            suffix: "android.zip"
          }
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-${{ github.ref_name }}
    - name: Make release artifacts
      run: |
        ${{ matrix.config.command }} gfxreconstruct-${{ github.ref_name }}-${{ matrix.config.suffix }} gfxreconstruct-${{ github.ref_name }}
    - name: Upload release artifacts
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" \
          ./gfxreconstruct-${{ github.ref_name }}-${{ matrix.config.suffix }}
